### ISSUE TITLE
Implement RFC 0001: BP_HTTPD_VERSION to request version

### ISSUE THREAD

**Issue by arjun024** [paketo-buildpacks/httpd#168]
See [RFC 0001: Buildpack.yml to Environment Variables](https://github.com/paketo-buildpacks/httpd/blob/main/rfcs/0001-buildpack-yml-to-env-var.md). 

The buildpack should support:
* Configuration using `$BP_HTTPD_VERSION `
* The buildpack should support both configuration options with environment variables taking priority
* The buildpack should detect whether the application has a buildpack.yml and print a message warning the deprecation of its use.

**Comment by sophiewigmore** [comment]
Docs PR: https://github.com/paketo-buildpacks/paketo-website/pull/132
