### ISSUE TITLE
httpd 0.3.0 BP_LIVE_RELOAD_ENABLED=true fails with "no buildpack groups passed detection"

### ISSUE THREAD

**Issue by nicks** [paketo-buildpacks/httpd#297]
## What happened?

Output

```
pack build example-httpd-image:tilt-build-pack-caching --path . --builder paketobuildpacks/builder:full --pull-policy if-not-present --buildpack gcr.io/paketo-buildpacks/httpd:0.3.0 --env BP_LIVE_RELOAD_ENABLED=true 
===> ANALYZING
===> DETECTING
ERROR: No buildpack groups passed detection.
ERROR: Please check that you are running against the correct path.
ERROR: failed to detect: no buildpacks participating
ERROR: failed to build: executing lifecycle: failed with status code: 20
```

## Build Configuration

* What platform (`pack`, `kpack`, `tekton` buildpacks plugin, etc.) are you
  using? Please include a version.

```
$ pack version
0.24.0+git-79a40b7.build-3148
```

* Can you provide a sample app or relevant configuration (`buildpack.yml`,
  `nginx.conf`, etc.)?

The app is here:

https://github.com/tilt-dev/tilt-extensions/tree/master/pack/test

Note that running with httpd 0.2.1 works fine:

```
pack build example-httpd-image:tilt-build-pack-caching --path . --builder paketobuildpacks/builder:full --pull-policy if-not-present --buildpack gcr.io/paketo-buildpacks/httpd:0.2.1 --env BP_LIVE_RELOAD_ENABLED=true 
```

Leaving off BP_LIVE_RELOAD_ENABLED also works.

## Checklist

* [x] I have included log output.
* [x] The log output includes an error message.
* [x] I have included steps for reproduction.

**Comment by nicks** [comment]
i can also repro this in the sample project:
https://github.com/paketo-buildpacks/samples/tree/main/httpd/httpd-sample

**Comment by arjun024** [comment]
Going by the tests here https://github.com/paketo-buildpacks/httpd/blob/v0.3.0/integration/simple_app_test.go#L90-L99,
it looks like you also need the watchexec buildpack when you enable live reload

**Comment by dmikusa-pivotal** [comment]
Prior to 0.3.0 this buildpack didn't support reloading. It was just silently ignoring `BP_LIVE_RELOAD_ENABLED`.

In 0.3.0, support has been added so when you enable `BP_LIVE_RELOAD_ENABLED` it expects to also have `watchexec` as this buildpack uses `watchexec` to restart the server.

What you need to do is also include the `watchexec` buildpack. 

```
pack build example-httpd-image:tilt-build-pack-caching --path . --builder paketobuildpacks/builder:full --pull-policy if-not-present --buildpack gcr.io/paketo-buildpacks/watchexec:2.3.3 --buildpack gcr.io/paketo-buildpacks/httpd:0.3.0 --env BP_LIVE_RELOAD_ENABLED=true
```

**Comment by dmikusa-pivotal** [comment]
@arjun024 is there any chance that we could make this work with the builder? Right now, if I just use the full builder, detection errors out for https://github.com/paketo-buildpacks/samples/tree/main/httpd/httpd-sample because it incorrectly thinks it is a Python app.

Users shouldn't generally need to add `--buildpack` flags. That's an extra complication. It also makes changes, like enabling reload support, less transparent. The user then need to know to add the `watchexec` buildpack which is not clear  from the error messages.

**Comment by ryanmoran** [comment]
I've added `watchexec` in the `httpd` order group for the full builder: https://github.com/paketo-buildpacks/full-builder/pull/569

**Comment by nicks** [comment]
thanks! this discussion helped my understanding a lot
