### ISSUE TITLE
Generate basic `http.conf` file when `BP_WEB_SERVER=httpd`

### ISSUE THREAD

**Issue by ryanmoran** [paketo-buildpacks/httpd#298]
## Summary
Implement the most basic case of Web Servers [RFC0004](https://github.com/paketo-buildpacks/rfcs/blob/main/text/web-servers/0004-zero-config.md). This case will generate a basic, valid `httpd.conf` file to be used by the start process when the `BP_WEB_SERVER` environment variable is set to `httpd`.

## Proposal
We'll need to figure out what the simplest possible `httpd.conf` file would look like to serve files from a directory. In this case, the default directory should be `/workspace/public`.

## Outcome
Given an application including a `/public` directory containing a set of static files, and not including an `httpd.conf` file, when I run `pack build myapp --buildpack paketo-buildpacks/httpd --env BP_WEB_SERVER=httpd` then I should see the application can be built and that the static files are served by HTTPD.

**Comment by ForestEckhardt** [comment]
The following seems to be what Apache suggests as a minimal http.conf https://cwiki.apache.org/confluence/display/HTTPD/Minimal+Config
