### ISSUE TITLE
Allow HTTPS to be enforced via environment variable

### ISSUE THREAD

**Issue by ryanmoran** [paketo-buildpacks/httpd#302]
## Summary
Implement the [HTTPS Enforcement](https://github.com/paketo-buildpacks/rfcs/blob/main/text/web-servers/0004-zero-config.md#https-enforcement) configuration settings for Web Servers RFC0004.

## Proposal
When the `BP_WEB_SERVER_FORCE_HTTPS` environment variable is set to `true`, the buildpack will generate configuration in the `httpd.conf` file that forces `http` requests to be redirected to `https` endpoints. Check out https://cwiki.apache.org/confluence/display/httpd/redirectssl for details on how to configure this in `httpd.conf`.

## Outcome
Given an application with no `httpd.conf` file, when we run `pack build myapp --buildpack paketo-buildpacks/httpd --env BP_WEB_SERVER=httpd --env BP_WEB_SERVER_FORCE_HTTPS=true`, then we should see the application can be built and that the static files are served by HTTPD with `http` requests being redirected to `https`.

**Comment by ForestEckhardt** [comment]
https://httpd.apache.org/docs/2.4/bind.html

**Comment by ForestEckhardt** [comment]
Scratch the above comment. Use this directive instead https://cwiki.apache.org/confluence/display/HTTPD/RewriteHTTPToHTTPS
