### ISSUE TITLE
Auto generated config fails

### ISSUE THREAD

**Issue by max-allan-surevine** [paketo-buildpacks/httpd#348]
If you try to auto generate the config it does not create valid config.

```
mkdir foo
cd foo
touch index.html
pack build httpd --builder paketobuildpacks/builder:full --env BP_WEB_SERVER=httpd
```

## Expected Behavior
The container should create a default config that works.

## Current Behavior
The container fails to run 
```
docker run -e PORT=8080 httpd
AH00526: Syntax error on line 20 of /workspace/httpd.conf:
DocumentRoot '/workspace/public' is not a directory, or is not readable
```

## Possible Solution
Maybe update the documentation to say your HTML files need to be in ./public

It'd also be handy to point out that you need to specify the port when running the container.

## Steps to Reproduce
See above

## Motivations
I was trying to get started with a very basic container.

**Comment by ryanmoran** [comment]
We should certainly update the documentation to include some details about the assumptions made by the auto-generated configuration. To change the path to serve, did you see the [docs](https://paketo.io/docs/howto/web-servers/#set-the-root-directory-for-static-files) for setting `BP_WEB_SERVER_ROOT`?

**Comment by max-allan-surevine** [comment]
Exactly those docs.

> Set the BP_WEB_SERVER_ROOT variable to an absolute file path or a file path relative to /workspace

So, if BP_WEB_SERVER_ROOT is  unset then the root would be /workspace, not /workspace/public.
